#!/bin/sh
cd /boot/home/projects/vstm-gui/PackagingFolder
package create -b vstm_1.0-8_gcc2.hpkg
sleep 0.5
package add vstm_1.0-8_gcc2.hpkg data documentation apps bin
sleep 0.5
addattr BeShare:Info "Simple TODO list manager with graphical front-end" vstm_1.0-8_gcc2.hpkg
becopy vstm_1.0-8_gcc2.hpkg "/Storage/Haiku/My ports"
mv vstm_1.0-8_gcc2.hpkg /boot/home/projects/repo2
sync